echo "We are trying this practical from linux EC2"
echo "We are from batch-31 making changes from Branch2 and learning git/gihub"
echo "We are from batch-31 and learning git/gihub"
echo "To check Fetch feature"
echo "This is from main brach commit"